/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SENSOR_PB_H_INCLUDED
#define PB_SENSOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SensorData {
    float temperature;
    float humidity;
    uint64_t timestamp;
    uint64_t interval;
} SensorData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorData_init_default                  {0, 0, 0, 0}
#define SensorData_init_zero                     {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SensorData_temperature_tag               1
#define SensorData_humidity_tag                  2
#define SensorData_timestamp_tag                 3
#define SensorData_interval_tag                  4

/* Struct field encoding specification for nanopb */
#define SensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          2) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         3) \
X(a, STATIC,   SINGULAR, UINT64,   interval,          4)
#define SensorData_CALLBACK NULL
#define SensorData_DEFAULT NULL

extern const pb_msgdesc_t SensorData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorData_fields &SensorData_msg

/* Maximum encoded size of messages (where known) */
#define SENSOR_PB_H_MAX_SIZE                     SensorData_size
#define SensorData_size                          32

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
